import Head from 'next/head'
import { useAuth } from '../context/AuthContext'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../Components/Parent'
import Link from 'next/link'
import LoginPage from '../Components/LoginPage'

export default function Home({Menu}) {
  const {auth,setAuth} = useAuth()

  return (
    <div className={styles.container}>
      <Head>
        <title>POS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {auth ?

      <Sidebar>
        <div className="Menu-List">
          {Menu.map((item,i) =>{
            return (
              <Link href="/" key={i}>
                <div className="Menu-Choice">
                  <div className="Menu-Image">
                    <Image src="https://cdn.mygingergarlickitchen.com/images/800px/800px-Food-Styling-indian-roti-recipe-phulka-chapati-Pinterest.jpg" width="200" height="200" alt="Roti"/>
                  </div>
                    <div className="Menu-Name">
                      <p key={item._id}>{item.MenuName}</p>
                    </div>
                </div>
              </Link>
            )
          })}
        </div>
      </Sidebar>

      : <LoginPage/> }

    </div>
  )
}

export const getServerSideProps = async () =>{
      const  res = await fetch("https://point-of-sale-backend.vercel.app/menu/getAllmenu",{method:'GET'}) 
      const data = await res.json()
      return {
        props : {Menu : data}
      } 
} 
